pushing_left/poses:
  header:
     frame_id: yumi_body
  pose:
    position:
      x: 0.4
      y: 0.2
      z: 0.3
    orientation:
      x: 0
      y: 1
      z: 0
      w: 0

pushing_right/poses:
  header:
     frame_id: yumi_body
  pose:
    position:
      x: 0.4
      y: -0.2
      z: 0.3
    orientation:
      x: 1
      y: 0
      z: 0
      w: 0

calibration_rel_wrist/left/pose:
  header:
     frame_id: yumi_palm_l
  pose:
    position:
      x: 0.
      y: 0.
      z: 0.05132
    orientation:
      x: 0
      y: 0
      z: 0
      w: 1

calibration_rel_wrist/right/pose:
  header:
     frame_id: yumi_palm_r
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.05132
    orientation:
      x: 0
      y: 0
      z: 0
      w: 1

gel/calibration/tool/points: [[561.26, 61.62, 103.58, 0.0, 0.92403, -0.38232, 0.00],
                          [560.67, 78.08, 103.58, 0.0, 0.92403, -0.38232, 0.00],
                          [535.47, 81.59, 103.58, 0.0, 0.92403, -0.38232, 0.00],
                          [535.47, 61.27, 103.58, 0.0, 0.92403, -0.38232, 0.00]]

camera/calibration/tool/points: [[446.44,96.75,56.03,0.0,0.89972,0.43648,0.0],
                          [445.16,197.07,56.03,0.0,0.89972,0.43648,0.0],
                          [345.18,195.48,56.03,0.0,0.89972,0.43648,0.0],
                          [345.96,95.73,56.03,0.0,0.89972,0.43648,0.0]]
                          
camera_dlsr/calibration/tool/points: [[446.44,96.75,56.03,0.0,0.89972,0.43648,0.0],
                          [445.16,197.07,56.03,0.0,0.89972,0.43648,0.0],
                          [345.18,195.48,56.03,0.0,0.89972,0.43648,0.0],
                          [345.96,95.73,56.03,0.0,0.89972,0.43648,0.0]]


camera/calibration/tool/points/yumi/right: [[458.56, -79.45, 282.89, 0.28680, 0.80587, 0.32704, -0.40171],
                          [430.19, -59.98, 276.97, 0.33978, 0.78952, 0.32831, -0.39169],
                          [417.58, -72.11, 292.27, 0.42139, 0.76441, 0.27421, -0.40364],
                          [433.95, -84.95, 292.19, 0.51806, 0.75863, 0.24443, -0.31040]]


gel/calibration/tool/ground: [421.34,
                          -59.01,
                          49.50,
                          0.0,
                          -0.46938,
                          -0.88299,
                          0.]

pushing/right/robot_convention/joints: [1.6186728267172805,
                       -0.627957447708273,
                       -2.181258817200459,
                       0.6194790456943977,
                       3.286937582146461,
                       0.7514464459671322,
                       -3.038332444527036]

pushing/left/robot_convention/joints: [-0.8759314115583274,
                     -1.5008775144531517,
                     1.5611336697750984,
                     0.5415813719525806,
                     2.4631588845619383,
                     0.5179680763672723,
                     1.5100636942652095]

pulling/left/yumi_convention/joints: [-24.12,
                                        -57.7,
                                        4,
                                        36.59,
                                        32.3,
                                        0,
                                        75.55]

pulling/right/yumi_convention/joints: [23.866943181519986,
                                       -59.47703384874138,
                                       14.881201257075713,
                                       24.265247301447943,
                                       90.87448527880477,
                                       116.39647833198862,
                                       -83.08584853107506]

pushing/active/left/yumi_convention/joints: [-72.63,
                                      -47.92,
                                      4.11,
                                      -72.92,
                                      -38.92,
                                      -44.15,
                                      96.14]

pushing/active/right/yumi_convention/joints: [71.30,
                                       -52.80,
                                       6.09,
                                       69.83,
                                       -45.67,
                                       -133.35,
                                       -91.13]

pushing/inactive/left/yumi_convention/joints: [-27.14, -83.11, 1.81, 29.45, 44.58, -95.63, 62.53]

pushing/inactive/right/yumi_convention/joints: [23.68, -75.95, -3.04, -27.75, 48.20, -88.61, -59.61]

#~ grasping_left/yumi_convention/joints: [-101.3,
                                       #~ -127.52,
                                       #~ 47.51,
                                       #~ 173.02,
                                       #~ 119.02,
                                       #~ 178.05,
                                       #~ 35.65]

#~ grasping_right/yumi_convention/joints: [95.84,
                                        #~ -129.82,
                                        #~ 44.86,
                                        #~ -165.5,
                                        #~ 111.79,
                                        #~ 5.68,
                                        #~ -35.94]
grasping_left/yumi_convention/joints: [-61.75, -121.39, 57.41, 148.95, 103.89, 151.29, 57.01]

grasping_right/yumi_convention/joints: [56.93, -125.18, 48.46, -144.46, 88.73, 6.46, -56.81]


levering_left/yumi_convention/joints: [-61.75, -121.39, 57.41, 148.95, 103.89, 151.29, 57.01]

levering_right/yumi_convention/joints: [56.93, -125.18, 48.46, -144.46, 88.73, 6.46, -56.81]

grasping_left/robot_convention/joints: [-0.8759314115583274,
                                        -1.008775144531517,
                                        1.5611336697750984,
                                        0.5415813719525806,
                                        2.3,
                                        0.5179680763672723,
                                        1.5100636942652095]

grasping_right/robot_convention/joints: [1.6186728267172805,
                                         -0.627957447708273,
                                         -2.181258817200459,
                                         0.6194790456943977,
                                         3.286937582146461,
                                         0.7514464459671322,
                                         -3.038332444527036]

go_home/left/yumi_convention/joints: [-62.28,
                                      -38.87,
                                      -10.6,
                                      101.47,
                                      10.51,
                                      -195.58,
                                      58.5]


go_home/right/yumi_convention/joints: [46.02,
                                       -51.22,
                                       -23.18,
                                       -58.02,
                                       13.43,
                                       -4.29,
                                       -47.7]

joint_limits/yumi_convention/left: [[-2.8, 2.8],
                                    [-2.4, .74],
                                    [-2.1, 1.3],
                                    [-5.0, 5.],
                                    [-1.27, 2.4],
                                    [-3.9, 3.9],
                                    [-2.9, 2.9]]

joint_limits/yumi_convention/right: [[-2.8, 2.8],
                                    [-2.4, .74],
                                    [-2.1, 1.3],
                                    [-5.0, 5.],
                                    [-1.27, 2.4],
                                    [-3.9, 3.9],
                                    [-2.9, 2.9]]
transform/tip_to_wrist: [0.0, -0.071399, 0.14344421, 0.0, 0.0, 0.0, 1.0]
